### ISSUE TITLE
Registration error due to unicode to utf-8 decode error

### ISSUE THREAD

**Issue by szepeviktor** [candango/automatoes#103]
```
# manuale register viktor-appfut@szepe.net
Candango Automatoes 0.9.7. Manuale replacement.


You're about to register a new account with e-mail viktor-appfut@szepe.net as contact. Continue? [Y/n] y
Oops! An unhandled error occurred. Please file a bug.
'utf-8' codec can't decode byte 0xc3 in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/opt/automatoes/lib/python3.9/site-packages/automatoes/cli.py", line 348, in manuale_main
    args.func(args)
  File "/opt/automatoes/lib/python3.9/site-packages/automatoes/cli.py", line 121, in _register
    register(
  File "/opt/automatoes/lib/python3.9/site-packages/automatoes/register.py", line 46, in register
    if not confirm("You're about to register a new account with e-mail "
  File "/opt/automatoes/lib/python3.9/site-packages/automatoes/helpers.py", line 22, in confirm
    answer = input("{} [{}] ".format(msg, choices)).strip().lower()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: invalid continuation byte
```

@piraz Could you help?

**Comment by szepeviktor** [comment]
Could it be that I typed an UTF-8 character on my Hungarian keyboard?
Or typed and deleted half of it?

**Comment by piraz** [comment]
Is that still happening?

**Comment by piraz** [comment]
We can try this: https://stackoverflow.com/a/47963812/2887989

**Comment by szepeviktor** [comment]
> We can try this

Yes please.
(btw i do not speak python)

**Comment by piraz** [comment]
Are still using python 3.6?

**Comment by szepeviktor** [comment]
> File "/opt/automatoes/lib/python3.9/site-packages/automatoes/cli.py", line 121

No.
I use 3.9

**Comment by piraz** [comment]
Are you able to patch your automatoes @szepeviktor for a test in your side?

Here are the files:

 - https://github.com/candango/automatoes/blob/develop/automatoes/helpers.py
 - https://github.com/candango/automatoes/blob/develop/automatoes/register.py

I'm forcing the input to encode and decode with utf-8 and ignoring errors.

Not able to reproduce the error on my side. Trying to figure out how to inject a non utf-8 to produce the error, but I'm accepting anything...

By the way, the error seems to be on the y/n answer not in the email:
```
File "/opt/automatoes/lib/python3.9/site-packages/automatoes/helpers.py", line 22, in confirm
    answer = input("{} [{}] ".format(msg, choices)).strip().lower()
```

**Comment by piraz** [comment]
Or I can create a pre-release so we can verify in your side...

**Comment by piraz** [comment]
Please test with:

`pip install --upgrade automatoes==0.9.8b1`

**Comment by piraz** [comment]
It is broken, let me see what is going on...

**Comment by szepeviktor** [comment]
All right. Right now I'm debugging another problem in another software.

**Comment by piraz** [comment]
This is working as supposed to be. You can test with:

`pip install --upgrade automatoes==0.9.8b3`

**Comment by szepeviktor** [comment]
Thank you.

**Comment by piraz** [comment]
@szepeviktor can you confirm if the issue was fixed?

**Comment by szepeviktor** [comment]
I could reproduce the error on 0.9.7 by typing `ű` and pressing backspace.

**Comment by szepeviktor** [comment]
I'm sorry to report.

```
Oops! An unhandled error occurred. Please file a bug.
'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 313, in manuale_main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 85, in _register
    register(
  File "/usr/local/lib/python3.9/dist-packages/automatoes/register.py", line 48, in register
    if not confirm("You're about to register a new account with e-mail "
  File "/usr/local/lib/python3.9/dist-packages/automatoes/helpers.py", line 22, in confirm
    answer = input(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data
```

```
$ manuale version
automatoes 0.9.8b3
```

locale: en_US.utf8

**Comment by szepeviktor** [comment]
Last time the first byte of UTF-8 character was in the error message, now the second one.

**Comment by piraz** [comment]
Fun, fun, fun ... good thing we can do the pre-release.

I think the issue lies on the fact your input seems to be utf-16 instead of utf-8. I'll got that tested....

Maybe I need to add a configuration letting the user change the encoding. The error is happening when you type `y` or `n` confirming that the new account will be registered. Would love to have what crazy `y` your keyboard is generating...

**Comment by szepeviktor** [comment]
> your input seems to be utf-16 instead of utf-8.

```
$ read I; echo $I | hd
ű
00000000  c5 b1 0a                                          |...|
00000003
```

Does it help?

**Comment by piraz** [comment]
I'm using right not the `sys.stdin.encoding`. Hope that will make it.

`pip install --upgrade automatoes==0.9.8b4`

**Comment by szepeviktor** [comment]
Oh nooo!
Once again

> 'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data

**Comment by szepeviktor** [comment]
Do you have an € sign on your keyboard?

I get a different error message with € + backspace.

> 'utf-8' codec can't decode bytes in position 0-1: unexpected end of data

**Comment by szepeviktor** [comment]
...because this sign is a 3-byte UTF-8 character

```
$ echo -n € | hd
00000000  e2 82 ac                                          |...|
00000003
```

**Comment by piraz** [comment]
I made a mistake. I need to use the input encoding to decode also, sorry.

I can reproduce the error:

```
input("test").encode("utf-16").decode()
test>? ű
Traceback (most recent call last):
  File "/usr/lib64/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by piraz** [comment]
There you go:

`pip install --upgrade automatoes==0.9.8b5`

**Comment by szepeviktor** [comment]
Once again

> 'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data

Could Python simply use readline to automatically handle console input?

**Comment by szepeviktor** [comment]
```
>>> import sys
>>> sys.stdin.encoding
'utf-8'
```
This is my encoding.

**Comment by szepeviktor** [comment]
Why does my backspace stroke delete only 1 byte? I've never seen this problem.

With this line of code input works okay.
```
>>> input("test: ").encode("utf-8").decode()
test: ű
'ű'
```

**Comment by piraz** [comment]
Used `click.confirm`, the new cli library I'll use to rewrite manuale and finish automatoes. This method seems to handle unicode and will create different type of prompt.

Lets see if it works:

`pip install --upgrade automatoes==0.9.8b6`

**Comment by szepeviktor** [comment]
Almost there.

```
$ manuale register viktor-appfut@szepe.net
Candango Automatoes 0.9.8b6. Manuale replacement.


You're about to register a new account with e-mail viktor-appfut@szepe.net as contact. Continue? [Y/n]:
Oops! An unhandled error occurred. Please file a bug.
'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data

...

  File "/usr/local/lib/python3.9/dist-packages/click/termui.py", line 234, in confirm
    value = visible_prompt_func(" ").lower().strip()
```

**Comment by piraz** [comment]
What is locale @szepeviktor? Run `locale`

**Comment by szepeviktor** [comment]
> What is locale

https://github.com/candango/automatoes/issues/103#issuecomment-1275707384

**Comment by szepeviktor** [comment]
What a debug release!!

**Comment by szepeviktor** [comment]
ű + backspace:

```
manuale register viktor-appfut@szepe.net
Candango Automatoes 0.9.8b7. Manuale replacement.


*********************************************************
Inside the confirm function!!!!


Please post the output at:
 https://github.com/candango/automatoes/issues/103
You're about to register a new account with e-mail viktor-appfut@szepe.net as contact. Continue? [Y/n]
Oops! An unhandled error occurred. Please file a bug.
'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 313, in manuale_main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 85, in _register
    register(
  File "/usr/local/lib/python3.9/dist-packages/automatoes/register.py", line 46, in register
    if not confirm("You're about to register a new account with e-mail "
  File "/usr/local/lib/python3.9/dist-packages/automatoes/helpers.py", line 30, in confirm
    answer, encoding = decode(input("%s [%s] " % (msg, choices)))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data
```

**Comment by szepeviktor** [comment]
ű + backspace + backspace

```
manuale register viktor-appfut@szepe.net
Candango Automatoes 0.9.8b7. Manuale replacement.


*********************************************************
Inside the confirm function!!!!


Please post the output at:
 https://github.com/candango/automatoes/issues/103
You're about to register a new account with e-mail viktor-appfut@szepe.net as contact. Continue? [Y/n]
*********************************************************
Answer:
Answer encoded with: ascii
Preferred encoding: UTF-8
Default locale:
 lang: en_US, encoding: UTF-8
Current input encoding: utf-8
Current output encoding: utf-8
Byte order: little
*********************************************************
Outside the confirm function!!!! Don't copy after the nextline of starts...
*********************************************************
Generating a new account key. This might take a second.
Oops! An unhandled error occurred. Please file a bug.
No module named '_cffi_backend'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 313, in manuale_main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 85, in _register
    register(
  File "/usr/local/lib/python3.9/dist-packages/automatoes/register.py", line 60, in register
    account = Account(key=generate_rsa_key(4096))
  File "/usr/local/lib/python3.9/dist-packages/automatoes/crypto.py", line 64, in generate_rsa_key
    return generate_private_key(65537, size, default_backend())
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/__init__.py", line 9, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 64, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```
I have cffi                1.15.1
and libffi-dev:amd64               3.3-6 and libffi7:amd64                  3.3-6

**Comment by piraz** [comment]
Wait. I'm looping until utf-32. Will be at the 0.9.8b8.

**Comment by piraz** [comment]
I think that will fix your issue, because I got the input response, I'll decode/encode to string from ascii to utf-32.

I was kind of afraid about getting an error strait on the input function, that was not the case.

That last exception is kind of something else ... verifying later.

**Comment by szepeviktor** [comment]
0.9.8b8 produces the same output with 1 or 2 backspaces as above.

**Comment by piraz** [comment]
Output?

**Comment by szepeviktor** [comment]
> Output?

copy-pasted here https://github.com/candango/automatoes/issues/103#issuecomment-1279195072

**Comment by szepeviktor** [comment]
My cursor moves one column to the left at the first backspace keystroke and another column at the second one.

![kép](https://user-images.githubusercontent.com/952007/195894872-8a6f945d-8f1b-4f83-a572-d289016f805f.png)

**Comment by piraz** [comment]
UnicodeDecodeError..... Haaaaaaaaa

**Comment by piraz** [comment]
Published... 0.9.8b9

**Comment by szepeviktor** [comment]
All right!

```
manuale register viktor-appfut@szepe.net
Candango Automatoes 0.9.8b9. Manuale replacement.


*********************************************************
Inside the confirm function!!!!


Please post the output at:
 https://github.com/candango/automatoes/issues/103
You're about to register a new account with e-mail viktor-appfut@szepe.net as contact. Continue? [Y/n]
*********************************************************
This exception is on the python input function WTF!?:
DECODING!!!!
'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data
*********************************************************
Preferred encoding: UTF-8
Default locale:
 lang: en_US, encoding: UTF-8
Current input encoding: utf-8
Current output encoding: utf-8
Byte order: little
*********************************************************
*********************************************************
Oops! An unhandled error occurred. Please file a bug.
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 313, in manuale_main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/automatoes/cli/__init__.py", line 85, in _register
    register(
  File "/usr/local/lib/python3.9/dist-packages/automatoes/register.py", line 46, in register
    if not confirm("You're about to register a new account with e-mail "
  File "/usr/local/lib/python3.9/dist-packages/automatoes/helpers.py", line 61, in confirm
    if "no encode found" in answer:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by piraz** [comment]
Lemme try something crazy here...

**Comment by piraz** [comment]
Ok, 0.9.8b10 will ignore that and keep asking for y, yes, n or no, exclusively.

Will produce more output...

**Comment by szepeviktor** [comment]
It works! 🎉 

```
*********************************************************
This exception is on the python input function WTF!?:
DECODING!!!!
'utf-8' codec can't decode byte 0xc5 in position 0: unexpected end of data
*********************************************************
Preferred encoding: UTF-8
Default locale:
 lang: en_US, encoding: UTF-8
Current input encoding: utf-8
Current output encoding: utf-8
Byte order: little
Setting answer to: UnicodeDecodeError
*********************************************************
*********************************************************
Dude, please type this: y, yes, n, no
No more ç/ű/etc... + backspace + backspace or whatever UnicodeDecodeError you can generate with your keyboard....
Fix here is just ignore.... and keep asking for valid responses
Answer: UnicodeDecodeError
Answer encoded with:
Preferred encoding: UTF-8
Default locale:
 lang: en_US, encoding: UTF-8
Current input encoding: utf-8
Current output encoding: utf-8
Byte order: little
*********************************************************
Outside the confirm function!!!! Don't copy after the nextline of starts...
*********************************************************
```

**Comment by piraz** [comment]
Are you able to input yes or no, right?

**Comment by piraz** [comment]
I'll also add a parameter to this command to bypass the input. Something like:

```
manuale register --agree my@e.mail 

or

manuale register -a my@e.mail 
```

This will bypass the input and consider the agreed answer as yes.

**Comment by szepeviktor** [comment]
> Are you able to input yes or no, right?

Yes.

Thank you!

**Comment by piraz** [comment]
I'll wrap this and publish 0.9.8, not right now, I'll review things before.

**Comment by piraz** [comment]
By the way, the `UnicodeDecodeError` is inside the `input`, witch is a [Build In](https://docs.python.org/3/library/functions.html) function, in c dude, in f... c.

This is being generated probably right here: https://github.com/python/cpython/blob/main/Python/bltinmodule.c#L2242. Or here: https://github.com/python/cpython/blob/main/Python/bltinmodule.c#L2180.

Would be great to have a function returning just bytes.
