### ISSUE TITLE
Cannot register account

### ISSUE THREAD

**Issue by phev8** [candango/automatoes#53]
I experience issues when trying to start the certificate workflow with account registration.
When calling:

`manuale register <account@email.com>`

the following error is displayed:

```
Oops! An unhandled error occurred. Please file a bug.
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/automatoes/cli.py", line 348, in manuale_main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/automatoes/cli.py", line 125, in _register
    key_file=args.key_file
  File "/usr/local/lib/python3.7/site-packages/automatoes/register.py", line 65, in register
    acmev2 = AcmeV2(server, account)
  File "/usr/local/lib/python3.7/site-packages/automatoes/acme.py", line 243, in __init__
    if self.is_uri_letsencrypt_acme_v1():
  File "/usr/local/lib/python3.7/site-packages/automatoes/acme.py", line 256, in is_uri_letsencrypt_acme_v1
    return "acme-v01.api.letsencrypt.org" in self.account.uri
TypeError: argument of type 'NoneType' is not iterable
```

This is using version 0.9.3 on a macOS most recent version.

**Comment by piraz** [comment]
Let's try `manuale register account@email.com`  without `<>`. 

I assume your're running something like this(with the `<>`):

> 
> `manuale register <account@email.com>`
> 

Is that the case?

**Comment by piraz** [comment]
Reproduced. This is bad. I'll put a hotfix for you.

**Comment by phev8** [comment]
Perfect. Thank you very much for the quick response. It works now (version 0.9.4).
